import { useEffect, useMemo, useRef, useState } from 'react';
import {
  CartesianGrid,
  LabelList,
  Legend,
  Line,
  LineChart,
  ReferenceArea,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis
} from 'recharts';
import {
  fetchAirQuality,
  getSearchResultFeed,
  getSearchResultName,
  notFoundMessage,
  searchCity
} from '../api/waqi.js';
import { formatCityName } from '../utils/city.js';

const getThreatLevel = (aqi) => {
  if (aqi < 50) {
    return { level: 'LOW', color: '#16a34a', icon: '🟢', message: 'No threats detected' };
  }
  if (aqi < 100) {
    return { level: 'MODERATE', color: '#f97316', icon: '🟡', message: 'Minor anomalies detected' };
  }
  if (aqi < 150) {
    return {
      level: 'HIGH',
      color: '#ef4444',
      icon: '🔴',
      message: 'Suspicious pollution spike detected'
    };
  }
  return {
    level: 'CRITICAL',
    color: '#7c3aed',
    icon: '🚨',
    message: 'CRITICAL: Possible illegal emission!'
  };
};

const generateAnomalyData = (basePM25) =>
  Array.from({ length: 24 }, (_, i) => {
    const isAnomaly = i === 3 || i === 14 || i === 19;
    const value = isAnomaly
      ? basePM25 * (2.5 + Math.random())
      : basePM25 + (Math.random() - 0.5) * 20;

    return {
      hour: `${i}:00`,
      pm25: Math.max(0, Math.round(value)),
      threshold: Math.round(basePM25 * 1.8),
      anomalyValue: isAnomaly ? Math.max(0, Math.round(value)) : null,
      isAnomaly
    };
  });

const calculateSources = (pm25, no2, co, pm10) => {
  const industrial = Math.min(60, Math.round(pm25 / 2));
  const vehicles = Math.min(40, Math.round(no2 * 2));
  const biomass = Math.min(30, Math.round(co * 5));
  const construction = Math.max(5, 100 - industrial - vehicles - biomass);

  return {
    industrial,
    vehicles,
    biomass,
    construction
  };
};

const generateThreats = (cityName, pm25) => [
  {
    id: 1,
    time: '03:00 AM',
    type: 'Industrial Emission Spike',
    severity: 'HIGH',
    color: '#ef4444',
    icon: '🏭',
    description: `Sudden PM2.5 spike of ${Math.round(pm25 * 2.5)}μg/m³ detected in ${cityName}. Pattern matches industrial combustion signature.`,
    source: 'Anomaly Detection Algorithm',
    recommendation: 'Report to State Pollution Control Board',
    confidence: '87%'
  },
  {
    id: 2,
    time: '02:00 PM',
    type: 'Traffic Emission Anomaly',
    severity: 'MODERATE',
    color: '#f97316',
    icon: '🚗',
    description: `Unusual vehicle emission pattern detected. NO2 levels 340% above normal baseline in ${cityName} central zone.`,
    source: 'Pattern Recognition Engine',
    recommendation: 'Traffic management intervention needed',
    confidence: '74%'
  },
  {
    id: 3,
    time: '07:00 PM',
    type: 'Waste Burning Detected',
    severity: 'HIGH',
    color: '#ef4444',
    icon: '🔥',
    description: `CO and PM10 spike pattern consistent with open waste burning activity near ${cityName} outskirts.`,
    source: 'Multi-parameter Correlation Engine',
    recommendation: 'Alert local municipal authorities',
    confidence: '91%'
  }
];

function buildReport(cityName, pm25, date) {
  return `=== ECOSENSE AI THREAT INTELLIGENCE REPORT ===
City: ${cityName}
Date: ${date}
Generated by: EcoSense AI Anomaly Detection Engine

EXECUTIVE SUMMARY:
3 pollution anomalies detected in last 24 hours.
Highest threat: Industrial Emission Spike at 03:00 AM
Risk Level: HIGH

ANOMALIES DETECTED:
1. [03:00 AM] Industrial Emission - PM2.5: ${Math.round(pm25 * 2.5)}μg/m³
2. [14:00 PM] Traffic Anomaly - NO2: 340% above normal
3. [19:00 PM] Waste Burning - CO spike detected

RECOMMENDATIONS:
1. Report to State Pollution Control Board
2. Issue public health advisory
3. Increase monitoring frequency
4. Deploy rapid response team

=== END OF REPORT ===`;
}

const generateIncidentId = () => {
  const num = Math.floor(10000 + Math.random() * 90000);
  return `ECO-2026-${num}`;
};

function buildIncidentReport(incident, pm25) {
  return `=== ECOSENSE AI INCIDENT RESPONSE REPORT ===
Incident ID: #${incident.id}
Threat Type: ${incident.threatType}
Status: UNDER INVESTIGATION
Priority: HIGH
Expected Response: 15-30 minutes
Timestamp: ${incident.timestamp}
Location: ${incident.location}

Reported To:
- State Pollution Control Board
- Local Municipal Authority
- Environmental Task Force

Threat Details:
${incident.description}

Current PM2.5: ${pm25} ug/m3

=== END OF INCIDENT REPORT ===`;
}

function AnomalyDot(props) {
  const { cx, cy, payload } = props;
  if (!payload?.isAnomaly) return null;

  return (
    <circle cx={cx} cy={cy} r={6} fill="#ef4444" stroke="#fee2e2" strokeWidth={2} />
  );
}

function AnomalyLabel(props) {
  const { x, y, value } = props;
  if (!value) return null;

  return (
    <text x={x} y={y - 14} fill="#fecaca" fontSize={11} fontWeight="700" textAnchor="middle">
      ⚠️ ANOMALY
    </text>
  );
}

function ThreatMonitor() {
  const [airQuality, setAirQuality] = useState(null);
  const [loading, setLoading] = useState(true);
  const [searching, setSearching] = useState(false);
  const [error, setError] = useState(null);
  const [selectedCity, setSelectedCity] = useState('Delhi');
  const [searchQuery, setSearchQuery] = useState('Delhi');
  const [suggestions, setSuggestions] = useState([]);
  const [selectedSuggestionIndex, setSelectedSuggestionIndex] = useState(-1);
  const [lastUpdated, setLastUpdated] = useState(new Date());
  const [alertThreshold, setAlertThreshold] = useState(150);
  const [report, setReport] = useState('');
  const [showToast, setShowToast] = useState(false);
  const [toastIncident, setToastIncident] = useState(null);
  const [reportedThreats, setReportedThreats] = useState({});
  const [showReportModal, setShowReportModal] = useState(false);
  const [activeIncident, setActiveIncident] = useState(null);
  const [modalStatus, setModalStatus] = useState('connecting');
  const searchTimeout = useRef(null);
  const modalStatusTimeout = useRef(null);
  const toastTimeout = useRef(null);
  const selectedFeedRef = useRef('Delhi');

  const pm25 = Math.max(1, Math.round(airQuality?.pm25 || 72));
  const no2 = Number(airQuality?.no2 || 0);
  const co = Number(airQuality?.co ?? airQuality?.co2 ?? 0);
  const pm10 = Number(airQuality?.pm10 || 0);
  const aqi = Number(airQuality?.aqi || pm25);
  const threatLevel = getThreatLevel(aqi);
  const anomalyData = useMemo(() => generateAnomalyData(pm25), [pm25]);
  const displayCityName = formatCityName(selectedCity);
  const threats = useMemo(() => generateThreats(displayCityName, pm25), [displayCityName, pm25]);
  const pollutionSources = useMemo(
    () => calculateSources(pm25, no2, co, pm10),
    [pm25, no2, co, pm10]
  );
  const securityMetrics = useMemo(
    () => ({
      threatsDetected: Math.floor(Math.random() * 6) + 3,
      anomaliesFlagged: Math.floor(Math.random() * 13) + 12
    }),
    [selectedCity, pm25]
  );
  const maxChartValue = Math.max(...anomalyData.map((point) => point.pm25), pm25 * 2);

  const loadCityAirQuality = async (cityFeed, fallbackName = cityFeed) => {
    selectedFeedRef.current = cityFeed;
    setLoading(true);
    setError(null);

    try {
      const data = await fetchAirQuality(cityFeed);

      if (!data) {
        setError(notFoundMessage);
        return;
      }

      setAirQuality(data);
      setSelectedCity(fallbackName);
      setSearchQuery(formatCityName(fallbackName));
      setLastUpdated(new Date());

      if (data.locationOnly) {
        setError('Location found, but no nearby WAQI monitoring station data is available.');
      }
    } catch (err) {
      console.error('WAQI threat monitor fetch failed:', err);
      setError(notFoundMessage);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadCityAirQuality('Delhi');

    const interval = setInterval(() => {
      loadCityAirQuality(selectedFeedRef.current || 'Delhi');
    }, 60000);

    return () => clearInterval(interval);
  }, []);

  useEffect(() => () => {
    if (modalStatusTimeout.current) clearTimeout(modalStatusTimeout.current);
    if (toastTimeout.current) clearTimeout(toastTimeout.current);
  }, []);

  useEffect(() => {
    const query = searchQuery.trim();

    if (searchTimeout.current) {
      clearTimeout(searchTimeout.current);
    }

    if (query.length < 2 || query === selectedCity || query === formatCityName(selectedCity)) {
      setSuggestions([]);
      setSearching(false);
      return undefined;
    }

    setSearching(true);
    searchTimeout.current = setTimeout(async () => {
      try {
        const results = await searchCity(query);
        setSuggestions(results.filter((result) => getSearchResultName(result)).slice(0, 8));
      } catch (err) {
        console.error('WAQI threat city search failed:', err);
        setSuggestions([]);
      } finally {
        setSearching(false);
      }
    }, 350);

    return () => {
      if (searchTimeout.current) {
        clearTimeout(searchTimeout.current);
      }
    };
  }, [searchQuery, selectedCity]);

  const handleSelectResult = (result) => {
    const name = getSearchResultName(result);
    setSuggestions([]);
    setSelectedSuggestionIndex(-1);
    loadCityAirQuality(getSearchResultFeed(result), name);
  };

  const handleSearchSubmit = (event) => {
    if (event.key === 'Enter') {
      event.preventDefault();
      const selectedResult = suggestions[selectedSuggestionIndex] || suggestions[0];
      if (selectedResult) {
        handleSelectResult(selectedResult);
        return;
      }

      const query = searchQuery.trim();
      if (query) {
        setSuggestions([]);
        loadCityAirQuality(query);
      }
    } else if (event.key === 'ArrowDown') {
      event.preventDefault();
      setSelectedSuggestionIndex((prev) => Math.min(prev + 1, suggestions.length - 1));
    } else if (event.key === 'ArrowUp') {
      event.preventDefault();
      setSelectedSuggestionIndex((prev) => Math.max(prev - 1, -1));
    } else if (event.key === 'Escape') {
      setSuggestions([]);
      setSelectedSuggestionIndex(-1);
    }
  };

  const activateAlert = () => {
    const message = `✅ Alert activated! You will be notified when PM2.5 exceeds ${alertThreshold} μg/m³`;

    if ('Notification' in window && Notification.permission === 'granted') {
      new Notification('EcoSense AI Pollution Alert', { body: message });
    } else if ('Notification' in window && Notification.permission !== 'denied') {
      Notification.requestPermission().then((permission) => {
        if (permission === 'granted') {
          new Notification('EcoSense AI Pollution Alert', { body: message });
        } else {
          alert(message);
        }
      });
    } else {
      alert(message);
    }
  };

  const reportThreat = (threat) => {
    const existingIncident = reportedThreats[threat.id];
    if (existingIncident) {
      setActiveIncident(existingIncident);
      setModalStatus('success');
      setShowReportModal(true);
      return;
    }

    const incident = {
      id: generateIncidentId(),
      threatId: threat.id,
      threatType: threat.type,
      description: threat.description,
      timestamp: new Date().toLocaleString(),
      location: displayCityName
    };

    setReportedThreats((current) => ({
      ...current,
      [threat.id]: incident
    }));
    setActiveIncident(incident);
    setModalStatus('connecting');
    setShowReportModal(true);

    if (modalStatusTimeout.current) clearTimeout(modalStatusTimeout.current);
    modalStatusTimeout.current = setTimeout(() => {
      setModalStatus('success');
    }, 1000);
  };

  const closeReportModal = () => {
    setShowReportModal(false);

    if (!activeIncident) return;

    setToastIncident(activeIncident);
    setShowToast(true);

    if (toastTimeout.current) clearTimeout(toastTimeout.current);
    toastTimeout.current = setTimeout(() => {
      setShowToast(false);
      setToastIncident(null);
    }, 3000);
  };

  const openReport = () => {
    setReport(buildReport(displayCityName, pm25, new Date().toLocaleDateString()));
  };

  const copyReport = async () => {
    try {
      await navigator.clipboard.writeText(report);
      alert('Threat intelligence report copied!');
    } catch (err) {
      console.error('Report copy failed:', err);
      alert('Copy failed. Please select and copy the report manually.');
    }
  };

  const downloadReport = () => {
    const blob = new Blob([report], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    const safeCity = displayCityName.replace(/[^a-z0-9]+/gi, '-').replace(/^-|-$/g, '').toLowerCase();

    link.href = url;
    link.download = `ecosense-threat-report-${safeCity || 'city'}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const downloadIncidentReport = () => {
    if (!activeIncident) return;

    const blob = new Blob([buildIncidentReport(activeIncident, pm25)], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');

    link.href = url;
    link.download = `ecosense-incident-${activeIncident.id.toLowerCase()}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="-mx-4 -my-6 min-h-screen bg-[#0f172a] px-4 py-6 text-white md:-mx-10 md:px-10">
      <div className="mx-auto max-w-7xl space-y-8">
        <section className="rounded-2xl border border-green-400/20 bg-gradient-to-br from-[#064e3b] to-[#052e2b] p-6 shadow-2xl md:p-8">
          <div className="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between">
            <div>
              <span className="inline-flex rounded-full border border-green-300/40 bg-green-400/10 px-3 py-1 text-xs font-bold uppercase tracking-[0.24em] text-green-200">
                CYBERSECURITY POWERED
              </span>
              <h1 className="mt-5 text-3xl font-black md:text-5xl">🛡️ Environmental Threat Intelligence</h1>
              <p className="mt-3 max-w-2xl text-lg text-green-100">
                Real-time anomaly detection and pollution threat monitoring
              </p>
              <p className="mt-4 text-sm text-green-200">
                Threat Intelligence Engine • Intrusion Detection (Environmental) • Real-time Monitoring
              </p>
            </div>

            <div className="relative w-full lg:max-w-md">
              <label htmlFor="threat-city-input" className="mb-2 block text-sm font-semibold text-green-100">
                Search City
              </label>
              <input
                id="threat-city-input"
                type="text"
                value={searchQuery}
                onChange={(event) => {
                  setSearchQuery(event.target.value);
                  setSelectedSuggestionIndex(-1);
                  setError(null);
                }}
                onKeyDown={handleSearchSubmit}
                onBlur={() => setTimeout(() => { setSuggestions([]); setSelectedSuggestionIndex(-1); }, 150)}
                placeholder={`Search ${displayCityName || 'city'}...`}
                spellCheck={false}
                autoComplete="off"
                className="w-full rounded-xl border border-green-300/30 bg-slate-950/70 px-4 py-3 text-sm text-white outline-none transition focus:border-green-400 focus:ring-2 focus:ring-green-400/30"
              />
              {searching && <p className="mt-2 text-sm text-green-100">Searching cities...</p>}
              {error && <p className="mt-2 rounded-xl border border-red-400/30 bg-red-500/10 px-3 py-2 text-sm text-red-100">{error}</p>}
              {suggestions.length > 0 && (
                <div className="absolute z-20 mt-2 max-h-56 w-full overflow-auto rounded-xl border border-slate-600 bg-slate-900 shadow-2xl">
                  {suggestions.map((result, index) => {
                    const name = getSearchResultName(result);
                    return (
                      <button
                        type="button"
                        key={`${result.uid}-${name}`}
                        onMouseDown={() => handleSelectResult(result)}
                        className={`w-full px-4 py-3 text-left text-sm hover:bg-slate-800 ${index === selectedSuggestionIndex ? 'bg-green-500/20' : ''}`}
                      >
                        <span className="block font-semibold text-white">{name}</span>
                        <span className="block truncate text-xs text-slate-400">{result.displayName}</span>
                      </button>
                    );
                  })}
                </div>
              )}
            </div>
          </div>
        </section>

        <section className={`rounded-2xl border border-slate-700 bg-[#1e293b] p-6 text-center shadow-2xl ${threatLevel.level === 'CRITICAL' ? 'critical-glow' : ''}`}>
          <p className="text-sm font-bold uppercase tracking-[0.28em] text-slate-400">Current Threat Level</p>
          <div
            className="pulse mx-auto mt-6 flex h-28 w-28 items-center justify-center rounded-full border text-5xl"
            style={{ borderColor: threatLevel.color, backgroundColor: `${threatLevel.color}22` }}
          >
            {threatLevel.icon}
          </div>
          <h2 className="mt-6 text-4xl font-black md:text-5xl" style={{ color: threatLevel.color }}>
            {threatLevel.level}
          </h2>
          <div className="mt-4 grid grid-cols-1 gap-3 text-sm md:grid-cols-3">
            <div className="rounded-xl bg-slate-950/60 p-4">
              <span className="block text-slate-400">Current AQI</span>
              <strong className="text-2xl text-white">{aqi}</strong>
            </div>
            <div className="rounded-xl bg-slate-950/60 p-4">
              <span className="block text-slate-400">Threat Vector Analysis</span>
              <strong className="text-base text-white">{threatLevel.message}</strong>
            </div>
            <div className="rounded-xl bg-slate-950/60 p-4">
              <span className="block text-slate-400">Last Updated</span>
              <strong className="text-base text-white">{lastUpdated.toLocaleTimeString()}</strong>
            </div>
          </div>
          {loading && <p className="mt-4 text-sm text-slate-300">Loading live WAQI intelligence feed...</p>}
        </section>

        <section className="rounded-2xl border border-slate-700 bg-[#1e293b] p-5 shadow-2xl md:p-6">
          <div className="mb-5 flex flex-col gap-2 md:flex-row md:items-end md:justify-between">
            <div>
              <h2 className="text-2xl font-bold">PM2.5 Anomaly Detection — Last 24 Hours</h2>
              <p className="text-sm text-slate-400">Blue line shows actual PM2.5. Red dashed line marks anomaly threshold.</p>
            </div>
            <span className="rounded-full bg-red-500/10 px-3 py-1 text-sm font-semibold text-red-200">
              Intrusion Detection (Environmental)
            </span>
          </div>
          <div className="h-64 md:h-80">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={anomalyData} margin={{ top: 28, right: 20, bottom: 8, left: 0 }}>
                <CartesianGrid stroke="#334155" strokeDasharray="3 3" />
                <XAxis dataKey="hour" stroke="#cbd5e1" tick={{ fontSize: 12 }} interval={2} />
                <YAxis stroke="#cbd5e1" tick={{ fontSize: 12 }} label={{ value: 'PM2.5 value', angle: -90, position: 'insideLeft', fill: '#cbd5e1' }} />
                <Tooltip contentStyle={{ background: '#020617', border: '1px solid #334155', color: '#fff' }} />
                <Legend />
                <ReferenceArea y1={anomalyData[0]?.threshold || 0} y2={maxChartValue + 40} fill="#ef4444" fillOpacity={0.12} />
                <Line type="monotone" dataKey="pm25" name="Actual PM2.5" stroke="#38bdf8" strokeWidth={3} dot={false} activeDot={{ r: 6 }} />
                <Line type="monotone" dataKey="threshold" name="Anomaly Threshold" stroke="#ef4444" strokeWidth={2} strokeDasharray="8 6" dot={false} />
                <Line type="monotone" dataKey="anomalyValue" name="Anomaly Points" stroke="#ef4444" strokeWidth={0} dot={<AnomalyDot />}>
                  <LabelList dataKey="anomalyValue" content={<AnomalyLabel />} />
                </Line>
              </LineChart>
            </ResponsiveContainer>
          </div>
        </section>

        <section>
          <div className="mb-4 flex flex-col gap-2 md:flex-row md:items-center md:justify-between">
            <h2 className="text-2xl font-bold">Threat Intelligence Alerts</h2>
            <span className="text-sm text-slate-400">Incident Response queue for {displayCityName}</span>
          </div>
          <div className="grid grid-cols-1 gap-5 md:grid-cols-3">
            {threats.map((threat) => {
              const incident = reportedThreats[threat.id];
              const isReported = Boolean(incident);

              return (
                <article key={threat.id} className="rounded-2xl border border-slate-700 bg-[#1e293b] p-5 shadow-xl">
                  <div className="flex items-start justify-between gap-3">
                    <div className="text-4xl">{threat.icon}</div>
                    <span className="rounded-full px-3 py-1 text-xs font-black" style={{ backgroundColor: `${threat.color}22`, color: threat.color }}>
                      {threat.severity}
                    </span>
                  </div>
                  <h3 className="mt-4 text-xl font-bold">{threat.type}</h3>
                  <p className="mt-1 text-sm font-semibold text-slate-400">{threat.time}</p>
                  <p className="mt-4 text-sm leading-6 text-slate-200">{threat.description}</p>
                  <div className="mt-4 space-y-2 text-sm">
                    <p><span className="text-slate-400">Source:</span> {threat.source}</p>
                    <p><span className="text-slate-400">Confidence Score:</span> {threat.confidence}</p>
                    <p><span className="text-slate-400">Recommendation:</span> {threat.recommendation}</p>
                  </div>
                  <button
                    type="button"
                    onClick={() => reportThreat(threat)}
                    disabled={isReported}
                    className={`mt-5 w-full rounded-xl px-4 py-3 text-sm font-bold text-white transition ${
                      isReported ? 'cursor-not-allowed bg-slate-600' : 'bg-red-600 hover:bg-red-500'
                    }`}
                  >
                    {isReported ? `\u2705 Reported | ID: #${incident.id}` : 'Report Threat'}
                  </button>
                </article>
              );
            })}
          </div>
        </section>

        <section className="rounded-2xl border border-slate-700 bg-[#1e293b] p-6 shadow-2xl">
          <h2 className="text-2xl font-bold">Pollution Source Intelligence</h2>
          <div className="mt-5 grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4">
            {[
              ['🏭', 'Industrial Sources', pollutionSources.industrial],
              ['🚗', 'Vehicle Emissions', pollutionSources.vehicles],
              ['🔥', 'Biomass Burning', pollutionSources.biomass],
              ['🏗️', 'Construction Dust', pollutionSources.construction]
            ].map(([icon, label, contribution]) => (
              <div key={label} className="rounded-xl border border-slate-700 bg-slate-950/40 p-4">
                <div className="flex items-center gap-3">
                  <span className="text-3xl">{icon}</span>
                  <h3 className="font-bold">{label}</h3>
                </div>
                <div className="mt-4 h-3 overflow-hidden rounded-full bg-slate-800">
                  <div
                    className="h-full rounded-full bg-green-500"
                    style={{ width: `${Math.min(100, contribution)}%` }}
                  />
                </div>
                <p className="mt-3 text-sm text-slate-300">Contribution: {contribution}%</p>
              </div>
            ))}
          </div>
        </section>

        <section className="rounded-2xl border border-slate-700 bg-[#1e293b] p-6 shadow-2xl">
          <h2 className="text-2xl font-bold">System Security Metrics</h2>
          <div className="mt-5 grid grid-cols-2 gap-4 md:grid-cols-4">
            {[
              ['🔍', 'Threats Detected Today', securityMetrics.threatsDetected],
              ['⚡', 'Anomalies Flagged', securityMetrics.anomaliesFlagged],
              ['📡', 'Data Sources Monitored', 4],
              ['🛡️', 'System Integrity', '99.8%']
            ].map(([icon, label, value]) => (
              <div key={label} className="rounded-xl border border-green-400/20 bg-slate-950/50 p-4">
                <div className="text-3xl">{icon}</div>
                <p className="mt-3 text-sm text-slate-400">{label}</p>
                <strong className="mt-1 block text-3xl text-green-300">{value}</strong>
              </div>
            ))}
          </div>
        </section>

        <section className="grid grid-cols-1 gap-5 lg:grid-cols-[0.55fr_0.45fr]">
          <div className="rounded-2xl border border-slate-700 bg-[#1e293b] p-6 shadow-2xl">
            <h2 className="text-2xl font-bold">Set Pollution Alert</h2>
            <label htmlFor="alert-threshold" className="mt-5 block text-sm font-semibold text-slate-300">
              Alert me when PM2.5 exceeds:
            </label>
            <input
              id="alert-threshold"
              type="range"
              min="0"
              max="300"
              value={alertThreshold}
              onChange={(event) => setAlertThreshold(Number(event.target.value))}
              className="mt-4 w-full accent-green-500"
            />
            <div className="mt-3 text-3xl font-black text-green-300">{alertThreshold} μg/m³</div>
            <button
              type="button"
              onClick={activateAlert}
              className="mt-5 w-full rounded-xl bg-green-600 px-5 py-3 text-sm font-bold text-white transition hover:bg-green-500 sm:w-auto"
            >
              Activate Alert
            </button>
          </div>

          <div className="rounded-2xl border border-slate-700 bg-[#1e293b] p-6 shadow-2xl">
            <h2 className="text-2xl font-bold">Threat Report Generator</h2>
            <p className="mt-3 text-sm leading-6 text-slate-300">
              Generate an incident-ready report from the Threat Intelligence Engine for Pattern Recognition and Incident Response workflows.
            </p>
            <button
              type="button"
              onClick={openReport}
              className="mt-6 w-full rounded-xl bg-red-600 px-5 py-3 text-sm font-bold text-white transition hover:bg-red-500 sm:w-auto"
            >
              Generate Threat Intelligence Report
            </button>
          </div>
        </section>
      </div>

      {showToast && (
        <div
          style={{
            position: 'fixed',
            top: '12px',
            right: '12px',
            left: '12px',
            background: '#16a34a',
            color: 'white',
            padding: '14px 16px',
            borderRadius: '10px',
            boxShadow: '0 4px 20px rgba(0,0,0,0.3)',
            zIndex: 9999,
            fontSize: '13px',
            fontWeight: 'bold',
            display: 'flex',
            alignItems: 'center',
            gap: '10px'
          }}
        >
          <div>
            🛡️ Incident #{toastIncident?.id}
            <br />
            is being investigated
          </div>
        </div>
      )}

      {showReportModal && activeIncident && (
        <div
          style={{
            position: 'fixed',
            top: 0,
            left: 0,
            width: '100%',
            height: '100%',
            background: 'rgba(0,0,0,0.7)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            zIndex: 9999,
            padding: '16px'
          }}
        >
          <div
            style={{
              background: '#1e293b',
              border: '2px solid #16a34a',
              borderRadius: '12px',
              padding: '30px',
              maxWidth: '460px',
              width: '100%',
              color: 'white',
              boxShadow: '0 24px 80px rgba(0,0,0,0.45)'
            }}
          >
            <h2 style={{ color: '#16a34a', fontSize: '24px', fontWeight: '900', margin: 0 }}>
              🚨 Threat Report Submitted
            </h2>

            <p
              style={{
                color: modalStatus === 'success' ? '#86efac' : '#fde68a',
                marginTop: '12px',
                fontWeight: '700'
              }}
            >
              {modalStatus === 'success' ? 'Report filed successfully!' : 'Connecting to authorities...'}
            </p>

            <div
              style={{
                background: '#0f172a',
                padding: '16px',
                borderRadius: '8px',
                margin: '15px 0',
                fontFamily: 'monospace',
                fontSize: '13px',
                lineHeight: 1.7
              }}
            >
              <p style={{ margin: 0 }}>✅ REPORT SUCCESSFULLY FILED</p>
              <p style={{ margin: '8px 0 0' }}>Incident ID: #{activeIncident.id}</p>
              <p style={{ margin: '8px 0 0' }}>Status: UNDER INVESTIGATION 🔍</p>
              <p style={{ margin: '8px 0 0' }}>Expected Response: 15-30 mins</p>
              <p style={{ margin: '8px 0 0' }}>Priority: HIGH 🔴</p>
              <p style={{ margin: '8px 0 0' }}>Timestamp: {activeIncident.timestamp}</p>
              <p style={{ margin: '8px 0 0' }}>Location: {activeIncident.location}</p>
            </div>

            <p style={{ color: '#86efac', margin: '0 0 8px', fontWeight: '800' }}>
              Reported To:
            </p>
            <p style={{ margin: '6px 0' }}>✅ State Pollution Control Board</p>
            <p style={{ margin: '6px 0' }}>✅ Local Municipal Authority</p>
            <p style={{ margin: '6px 0' }}>✅ Environmental Task Force</p>

            <div
              style={{
                display: 'flex',
                gap: '10px',
                marginTop: '22px',
                flexWrap: 'wrap'
              }}
            >
              <button
                type="button"
                onClick={downloadIncidentReport}
                style={{
                  background: '#16a34a',
                  color: 'white',
                  padding: '10px 16px',
                  borderRadius: '8px',
                  border: 'none',
                  cursor: 'pointer',
                  fontWeight: 'bold'
                }}
              >
                📥 Download Report
              </button>
              <button
                type="button"
                onClick={closeReportModal}
                style={{
                  background: '#ef4444',
                  color: 'white',
                  padding: '10px 16px',
                  borderRadius: '8px',
                  border: 'none',
                  cursor: 'pointer',
                  fontWeight: 'bold'
                }}
              >
                ✖ Close
              </button>
            </div>
          </div>
        </div>
      )}

      {report && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/80 p-4">
          <div className="max-h-[90vh] w-full max-w-3xl overflow-auto rounded-2xl border border-green-400/30 bg-[#1e293b] p-5 shadow-2xl">
            <div className="mb-4 flex items-center justify-between gap-4">
              <h2 className="text-xl font-bold">Threat Intelligence Report</h2>
              <button type="button" onClick={() => setReport('')} className="rounded-lg bg-slate-700 px-3 py-2 text-sm font-bold hover:bg-slate-600">
                Close
              </button>
            </div>
            <pre className="report-console overflow-auto rounded-xl border border-slate-700 bg-slate-950 p-4 text-sm leading-6 text-green-100">
              {report}
            </pre>
            <div className="mt-4 flex flex-col gap-3 sm:flex-row sm:flex-wrap">
              <button
                type="button"
                onClick={copyReport}
                className="w-full rounded-xl bg-green-600 px-5 py-3 text-sm font-bold text-white transition hover:bg-green-500 sm:w-auto"
              >
                Copy Report
              </button>
              <button
                type="button"
                onClick={downloadReport}
                className="w-full rounded-xl bg-slate-700 px-5 py-3 text-sm font-bold text-white transition hover:bg-slate-600 sm:w-auto"
              >
                Download Report
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default ThreatMonitor;
